var wms_layers = [];


        var lyr_OpenTopoMap_0 = new ol.layer.Tile({
            'title': 'OpenTopoMap',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: '<a href="https://www.openstreetmap.org/copyright">Kartendaten: © OpenStreetMap-Mitwirkende, SRTM | Kartendarstellung: © OpenTopoMap (CC-BY-SA)</a>',
                url: 'https://a.tile.opentopomap.org/{z}/{x}/{y}.png'
            })
        });
var format_YOGYAKARTA_1 = new ol.format.GeoJSON();
var features_YOGYAKARTA_1 = format_YOGYAKARTA_1.readFeatures(json_YOGYAKARTA_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_YOGYAKARTA_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_YOGYAKARTA_1.addFeatures(features_YOGYAKARTA_1);
var lyr_YOGYAKARTA_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_YOGYAKARTA_1, 
                style: style_YOGYAKARTA_1,
                popuplayertitle: 'YOGYAKARTA',
                interactive: true,
    title: 'YOGYAKARTA<br />\
    <img src="styles/legend/YOGYAKARTA_1_0.png" /> 22 - 26<br />\
    <img src="styles/legend/YOGYAKARTA_1_1.png" /> 26 - 34.6<br />\
    <img src="styles/legend/YOGYAKARTA_1_2.png" /> 34.6 - 43.4<br />\
    <img src="styles/legend/YOGYAKARTA_1_3.png" /> 43.4 - 53.4<br />\
    <img src="styles/legend/YOGYAKARTA_1_4.png" /> 53.4 - 66<br />' });
var format_Lines_2 = new ol.format.GeoJSON();
var features_Lines_2 = format_Lines_2.readFeatures(json_Lines_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Lines_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Lines_2.addFeatures(features_Lines_2);
var lyr_Lines_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Lines_2, 
                style: style_Lines_2,
                popuplayertitle: 'Lines',
                interactive: true,
                title: '<img src="styles/legend/Lines_2.png" /> Lines'
            });
var format_Centroids_3 = new ol.format.GeoJSON();
var features_Centroids_3 = format_Centroids_3.readFeatures(json_Centroids_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Centroids_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Centroids_3.addFeatures(features_Centroids_3);
var lyr_Centroids_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Centroids_3, 
                style: style_Centroids_3,
                popuplayertitle: 'Centroids',
                interactive: true,
                title: '<img src="styles/legend/Centroids_3.png" /> Centroids'
            });

lyr_OpenTopoMap_0.setVisible(true);lyr_YOGYAKARTA_1.setVisible(true);lyr_Lines_2.setVisible(true);lyr_Centroids_3.setVisible(true);
var layersList = [lyr_OpenTopoMap_0,lyr_YOGYAKARTA_1,lyr_Lines_2,lyr_Centroids_3];
lyr_YOGYAKARTA_1.set('fieldAliases', {'WADMKC': 'WADMKC', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Perawat': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Perawat', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Bidan': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Bidan', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kefarmasian': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kefarmasian', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Masyarakat': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Masyarakat', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Lingkungan': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Lingkungan', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Gizi': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Gizi', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Medis': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Medis', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Kesehatan Psikologi Klinis': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Kesehatan Psikologi Klinis', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Keteknisan Medis': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Keteknisan Medis', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Teknik Biomedika': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Teknik Biomedika', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Total Tenaga Kesehatan': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Total Tenaga Kesehatan', });
lyr_Lines_2.set('fieldAliases', {'WADMKC': 'WADMKC', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Perawat': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Perawat', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Bidan': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Bidan', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kefarmasian': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kefarmasian', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Masyarakat': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Masyarakat', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Lingkungan': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Lingkungan', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Gizi': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Gizi', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Medis': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Medis', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Kesehatan Psikologi Klinis': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Kesehatan Psikologi Klinis', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Keteknisan Medis': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Keteknisan Medis', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Teknik Biomedika': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Teknik Biomedika', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Total Tenaga Kesehatan': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Total Tenaga Kesehatan', });
lyr_Centroids_3.set('fieldAliases', {'WADMKC': 'WADMKC', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Perawat': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Perawat', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Bidan': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Bidan', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kefarmasian': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kefarmasian', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Masyarakat': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Masyarakat', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Lingkungan': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Lingkungan', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Gizi': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Gizi', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Medis': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Medis', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Kesehatan Psikologi Klinis': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Kesehatan Psikologi Klinis', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Keteknisan Medis': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Keteknisan Medis', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Teknik Biomedika': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Teknik Biomedika', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Total Tenaga Kesehatan': 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Total Tenaga Kesehatan', });
lyr_YOGYAKARTA_1.set('fieldImages', {'WADMKC': 'TextEdit', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Perawat': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Bidan': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kefarmasian': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Masyarakat': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Lingkungan': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Gizi': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Medis': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Kesehatan Psikologi Klinis': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Keteknisan Medis': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Teknik Biomedika': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Total Tenaga Kesehatan': 'Range', });
lyr_Lines_2.set('fieldImages', {'WADMKC': '', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Perawat': '', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Bidan': '', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kefarmasian': '', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Masyarakat': '', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Lingkungan': '', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Gizi': '', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Medis': '', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Kesehatan Psikologi Klinis': '', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Keteknisan Medis': '', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Teknik Biomedika': '', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Total Tenaga Kesehatan': '', });
lyr_Centroids_3.set('fieldImages', {'WADMKC': 'TextEdit', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Perawat': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Bidan': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kefarmasian': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Masyarakat': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Lingkungan': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Gizi': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Medis': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Kesehatan Psikologi Klinis': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Keteknisan Medis': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Teknik Biomedika': 'Range', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Total Tenaga Kesehatan': 'Range', });
lyr_YOGYAKARTA_1.set('fieldLabels', {'WADMKC': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Perawat': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Bidan': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kefarmasian': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Masyarakat': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Lingkungan': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Gizi': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Medis': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Kesehatan Psikologi Klinis': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Keteknisan Medis': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Teknik Biomedika': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Total Tenaga Kesehatan': 'no label', });
lyr_Lines_2.set('fieldLabels', {'WADMKC': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Perawat': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Bidan': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kefarmasian': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Masyarakat': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Lingkungan': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Gizi': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Medis': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Kesehatan Psikologi Klinis': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Keteknisan Medis': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Teknik Biomedika': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Total Tenaga Kesehatan': 'no label', });
lyr_Centroids_3.set('fieldLabels', {'WADMKC': 'inline label - always visible', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Perawat': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Bidan': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kefarmasian': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Masyarakat': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Kesehatan Lingkungan': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Tenaga Kesehatan - Tenaga Gizi': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Medis': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Kesehatan Psikologi Klinis': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Keteknisan Medis': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Jumlah Tenaga Teknik Biomedika': 'no label', 'Jumlah Tenaga Kesehatan Menurut Kecamatan di Kota Yogyakarta, 2025 — Sheet1_Total Tenaga Kesehatan': 'inline label - visible with data', });
lyr_Centroids_3.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});